# Generated by Django 5.1.4 on 2025-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
