# Generated by Django 5.1.4 on 2025-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0002_alter_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(),
        ),
    ]
